# Generated by Django 5.2.3 on 2025-07-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_employee_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
    ]
